FROM nginx:latest
COPY web/assets /usr/share/nginx/html/assets
COPY web/images /usr/share/nginx/html/images
COPY web/index.html /usr/share/nginx/html/index.html
COPY default.conf /etc/nginx/conf.d/default.conf
