apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainsite
  namespace: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
      webapp: moqku.co
  template:
    metadata:
      labels:
        app: main
        webapp: moqku.co
    spec:
      containers:
      - name: mainsite
        image: victorbnnt/personal:main
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "Main"
---
apiVersion: v1
kind: Service
metadata:
  name: mainsite
  namespace: main
  labels:
    webapp: moqku.co
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: main
