apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landingpage
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: landing-page
            port:
              number: 80
