apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rewrite
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/articles)$ $1/ redirect;
      rewrite ^(/rain-in-australia)$ $1/ redirect;
      rewrite ^(/titanic)$ $1/ redirect;
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /articles(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: articles
            port:
              number: 80
      - path: /rain-in-australia(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: raininaustralia
            port:
              number: 80
      - path: /titanic(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: titanic
            port:
              number: 80
      #- path: /(.*)
      #  pathType: Prefix
      #  backend:
      #    service:
      #      name: landing-page
      #      port:
      #        number: 80
